export const COUNTRY_SET_ALL_LIST      = 'COUNTRY_SET_ALL_LIST';
export const COUNTRY_SET_SELECTED      = 'COUNTRY_SET_SELECTED';
export const COUNTRY_SET_FILTERED_LIST = 'COUNTRY_SET_FILTERED_LIST';
